// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbuvhrgzuhzwovvaxnpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhidXZocmd6dWh6d292dmF4bnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzU0MzEsImV4cCI6MjA2NTUxMTQzMX0.JvMyeQahreWwPLyV0bZJC1l3-2_W4CIYIvXw79OxUb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);